### ISSUE TITLE
How to make the build not read-only?

### ISSUE THREAD

**Issue by evandrocoan** [rctay/sublime-text-2-buildview#24]
### How to make the build panel {"panel": "output.exec"} not read-only?

Is there a option to accomplish so?

**Comment by rctay** [comment]
Hey, are you referring to the view that my plugin opens, or the default build panel that sublime shows when you run builds?

**Comment by evandrocoan** [comment]
The view sublime opens when is run:
```
   { "keys": ["f7"], "command": "build" }
```

**Comment by evandrocoan** [comment]
The view sublime opens when is run:
```
   { "keys": ["f7"], "command": "build" }
```
If I recall correctly, when I did not have this plugin, that view was editable.

**Comment by evandrocoan** [comment]
The view sublime opens when is run:
```
   { "keys": ["f7"], "command": "build" }
```
If I recall correctly, when I did not have this plugin, that view was editable.

**Comment by evandrocoan** [comment]
The view sublime opens when is run:
```
   { "keys": ["f7"], "command": "build" }
```
If I recall correctly, when I did not have this plugin, that view was editable.

**Comment by rctay** [comment]
Oh, I didn't know you could do that. I was able to enter text though. What version of sublime are you using?

**Comment by evandrocoan** [comment]
Now I am using `3126`. I just delete my data and tried to compile something and id worked, I could edit the output panel. This is my full install, if you want to try: https://github.com/evandrocoan/SublimeTextStudio

![image](https://cloud.githubusercontent.com/assets/5332158/18874926/0c0f2fae-849a-11e6-9e78-ea28ed8c537a.png)

**Comment by rctay** [comment]
If I understand your reply correctly, the behaviour described doesn't occur anymore. Hence closing, reopen if I was mistaken.

**Comment by evandrocoan** [comment]
Sorry, looks like I posted it on the wrong plugin. It is the https://github.com/aziz/SublimeANSI, which is doing the output panel to be read-only, when I am setting the target build as `ansi_color_build` on my `.sublime-build` file:
```json
    "build_systems":
    [
        {
            "working_dir": "$project_path/installers",

            "name": "Galileo Installer",
            "cmd": ["galileo.bat", "$project_path/plugins/addons/amxmodx/scripting/galileo.sma", "galileo", "$packages"],

            "target": "ansi_color_build",
            "syntax": "Packages/ANSIescape/ANSI.tmLanguage",
        },
    ]
```
