### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by saybinem** [rctay/sublime-text-2-buildview#30]
I am using sublime text 3 version 3126.The plugin automatically updated now the build output is not going to new tab and it only shows output in same tab down below?

**Comment by rctay** [comment]
Sorry to hear that. Can you have a look at the console (Ctrl-` on
Windows/Linux), any error messages?



On Oct 10, 2017 18:14, "Sohaib Asif" <notifications@github.com> wrote:

I am using sublime text 3 version 3126.The plugin automatically updated now
the build output is not going to new tab and it only shows output in same
tab down below?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rctay/sublime-text-2-buildview/issues/30>, or mute the
thread

**Comment by saybinem** [comment]
DPI scale: 1
startup, version: 3126 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/sohaib/.config/sublime-text-3/Packages
state path: /home/sohaib/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/sohaib/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.42556
warning: mnemonic t not found in menu caption Tools
startup time: 0.507048
first paint time: 0.511344
first paint time: 0.525041
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin All Autocomplete.all_views_completions
reloading plugin Angular CLI.Angular CLI
reloading plugin AngularJS.AngularJS-sublime-package
reloading plugin AngularJS.jscompletions
reloading plugin AngularJS.message
reloading plugin AngularJS.sublime_commands
reloading plugin AngularJS.viewlocation
reloading plugin Bower.Bower
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
reloading plugin Boxy Theme.BT
reloading plugin Boxy Theme.Icons
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Build Next.BuildNext
reloading plugin Copy Relative Path.copy_relative_path
reloading plugin Git Conflict Resolver.GitConflictResolver
reloading plugin HTMLBeautify.HTMLBeautify
reloading plugin Javascript Beautify.jsbeautify
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Python Output Format.PythonOutputFormat
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-flake8.linter
SublimeLinter: flake8 linter loaded 
reloading plugin TypescriptCompletion.TSCompletion
reloading plugin Undo Close Tab.UndoTabs
reloading plugin Virtualenv.commands
reloading plugin Virtualenv.integrations
reloading plugin Virtualenv.virtualenv_lib
reloading plugin sublime-text-2-buildview.commands
reloading plugin sublime-text-2-buildview.pipe_views
reloading plugin sublime-text-2-buildview.settings
reloading plugin JavaScript Completions._generated_2017_04_09_at_16_06_42
reloading plugin JavaScript Completions.reloader
reloading plugin Nodejs.Nodejs
reloading plugin Nodejs.__init__
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin PySide.sublime_pyside
reloading plugin Python Fix Imports.python_fiximports
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin Terminal.Terminal
reloading plugin TypeScript.main
2017-10-10 16:15:49,794: 139671901796160: WARNING: TypeScript plugin initialized.
plugins loaded
lang_service_enabled: True
Path of tsserver.js: /home/sohaib/.config/sublime-text-3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /home/sohaib/.config/sublime-text-3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /usr/bin/node
ref view not found
SublimeLinter: debug mode: off 
SublimeLinter: WARNING: flake8 deactivated, cannot locate 'flake8' 
warning: mnemonic t not found in menu caption Tools
Package Control: Installing 1 upgrades
ignored packages updated to: ["sublime-text-2-buildview", "Vintage"]
unloading plugin sublime-text-2-buildview.commands
unloading plugin sublime-text-2-buildview.pipe_views
unloading plugin sublime-text-2-buildview.settings
reloading settings Packages/User/Package Control.sublime-settings
warning: mnemonic t not found in menu caption Tools
reloading settings Packages/User/Preferences.sublime-settings
warning: mnemonic t not found in menu caption Tools
Running python -u "/home/sohaib/code/fnb-backend/funnelbeam/industryMapping.py"
Package Control: Upgraded sublime-text-2-buildview to 2017.10.09.14.09.43
ignored packages updated to: ["Vintage"]
reloading plugin sublime-text-2-buildview.commands
reloading plugin sublime-text-2-buildview.pipe_views
reloading plugin sublime-text-2-buildview.settings
warning: mnemonic t not found in menu caption Tools
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
warning: mnemonic t not found in menu caption Tools
reloading settings Packages/User/Preferences.sublime-settings
warning: mnemonic t not found in menu caption Tools
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 173, in run
AttributeError: 'module' object has no attribute 'EnabledSetting'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 119, in on_query_context
AttributeError: 'module' object has no attribute 'EnabledSetting'
Running python -u "/home/sohaib/code/fnb-backend/funnelbeam/industryMapping.py"
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 119, in on_query_context
AttributeError: 'module' object has no attribute 'EnabledSetting'
Running python -u "/home/sohaib/code/fnb-backend/funnelbeam/industryMapping.py"
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 173, in run
AttributeError: 'module' object has no attribute 'EnabledSetting'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 119, in on_query_context
AttributeError: 'module' object has no attribute 'EnabledSetting'
Running python -u "/home/sohaib/code/fnb-backend/funnelbeam/industryMapping.py"
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 119, in on_query_context
AttributeError: 'module' object has no attribute 'EnabledSetting'
Running python -u "/home/sohaib/code/fnb-backend/funnelbeam/industryMapping.py"
Could not import subprocess32 module, falling back to subprocess module
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 119, in on_query_context
AttributeError: 'module' object has no attribute 'EnabledSetting'
Running python -u "/home/sohaib/code/fnb-backend/funnelbeam/industryMapping.py"
Traceback (most recent call last):
  File "exec in /opt/sublime_text/Packages/Default.sublime-package", line 362, in finish
  File "exec in /opt/sublime_text/Packages/Default.sublime-package", line 303, in append_string
  File "exec in /opt/sublime_text/Packages/Default.sublime-package", line 124, in kill
  File "./python3.3/subprocess.py", line 1765, in terminate
    # sending input if we retry.
  File "./python3.3/subprocess.py", line 1760, in send_signal
    
ProcessLookupError: [Errno 3] No such process
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 119, in on_query_context
AttributeError: 'module' object has no attribute 'EnabledSetting'
Running python -u "/home/sohaib/code/fnb-backend/funnelbeam/industryMapping.py"
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 119, in on_query_context
AttributeError: 'module' object has no attribute 'EnabledSetting'
Running python -u "/home/sohaib/code/fnb-backend/funnelbeam/industryMapping.py"
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 173, in run
AttributeError: 'module' object has no attribute 'EnabledSetting'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "commands in /home/sohaib/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package", line 119, in on_query_context
AttributeError: 'module' object has no attribute 'EnabledSetting'
Running python -u "/home/sohaib/code/somefile.py

**Comment by saybinem** [comment]
You are calling the attribute which doesn't exsist or forget to pass

**Comment by rctay** [comment]
Can you restart and try running the build again?

**Comment by saybinem** [comment]
Its working fine thanks @rctay  can you elaborate how you fixed it

**Comment by rctay** [comment]
Glad to hear it's now working for you. I didn't change any code upstream, seems like old plugin code was still loaded in sublime and was being called from the new, updated code, so it seems a good 'ol restart was good enough to make it work for you.
