### ISSUE TITLE
Built-in build view pops up, then closes

### ISSUE THREAD

**Issue by rdeits** [rctay/sublime-text-2-buildview#9]
When running a build with buildview enabled, the "Build output" view shows up and works really nicely. However, sublime's built-in build view also pops up at the bottom of the screen, then disappears. Is that an expected behavior? And if so, is there any way to turn it off?

**Comment by rctay** [comment]
Thanks for dropping a comment @rdeits, I appreciate it!

Unfortunately, there's no way around this; as far as I know, sublime's built-in build view can't be disabled. If you look at our code [1], you'll see that what we are doing is mirroring/piping the text from the built-in view to our own "Build output" view, we don't replace it (cos we can't, not that I know of). I'll keep tabs on sublime 3's releases and see if this becomes possible someday.

[1] https://github.com/rctay/sublime-text-2-buildview/blob/dabfaf1814ffe62b8e17b50014b74894f570c756/commands.py#L124

**Comment by rdeits** [comment]
Okay, thanks!

**Comment by Birnbaum2001** [comment]
The build panel can be disabled by setting "show_panel_on_build" to false in the user settings. See also http://superuser.com/questions/538636/disable-build-window-when-building-in-sublime-text-2

cheers,
Birnbaum2001
